version: '3.9'
name: "bs_bot"
services:
  postgres:
    image: "postgres:17.4"
    restart: always
    env_file:
      - .env
    networks:
      - app
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  telegram_bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    networks:
      - app
networks:
  app:

volumes:
  postgres: